# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import licenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, unique=True)),
                ('poc_contact_name', models.CharField(max_length=120)),
                ('poc_contact_email', models.EmailField(max_length=254)),
                ('admin_poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.PositiveSmallIntegerField(choices=[('javascript_sdk', 0), ('ios_sdk', 1), ('android_sdk', 2)])),
                ('license_type', models.PositiveSmallIntegerField(choices=[('production', 0), ('evaluation', 1)])),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('expiration_datetime', models.DateTimeField(default=licenses.models.get_default_license_expiration)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.Client')),
            ],
        ),
    ]
